FROM mambaorg/micromamba

USER root
 
# Environment variables setup
ENV TZ=UTC \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    SHELL=/bin/bash

# Set timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    wget curl libz-dev unzip \
    procps \
    && rm -rf /var/lib/apt/lists/*

# Create working directory
RUN mkdir -p /biocloud
WORKDIR /biocloud

# Clone SeekSoulMethyl repository
RUN git clone https://github.com/seekgene/SeekSoulMethyl.git

# Set environment variables
ENV MAMBA_ROOT_PREFIX=/opt/conda
ENV PATH=/opt/conda/envs/seeksoulmethyl/bin:$PATH

# Create conda environment from conda_dependencies.yml
RUN micromamba env create -n seeksoulmethyl -f SeekSoulMethyl/conda_dependencies.yml && \
    micromamba install -n seeksoulmethyl bioconda::nextflow && \
    micromamba clean --all --yes



# Install SeekSoulMethyl dependence packages
RUN /opt/conda/envs/seeksoulmethyl/bin/pip install ./SeekSoulMethyl/dependence && \
    /opt/conda/envs/seeksoulmethyl/bin/pip install \
        ./SeekSoulMethyl/dependence/simpleqc/target/wheels/simpleqc-0.1.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl \
        ./SeekSoulMethyl/dependence/search-pattern/target/wheels/search_pattern-0.1.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl

# Clone and install custom ALLCools
RUN git clone https://github.com/seekgene/ALLCools.git && \
    /opt/conda/envs/seeksoulmethyl/bin/pip install ./ALLCools && \
    rm -rf ./ALLCools

# Clone and install custom Bismark
RUN git clone https://github.com/seekgene/Bismark.git && \
    cp -r ./Bismark/* /opt/conda/envs/seeksoulmethyl/bin/ && \
    chmod +x /opt/conda/envs/seeksoulmethyl/bin/bismark* && \
    chmod +x /opt/conda/envs/seeksoulmethyl/bin/deduplicate_bismark && \
    rm -rf ./Bismark

# Install ossutil
RUN curl -o ossutil-2.2.0-linux-amd64.zip https://gosspublic.alicdn.com/ossutil/v2/2.2.0/ossutil-2.2.0-linux-amd64.zip && \
    unzip ossutil-2.2.0-linux-amd64.zip && \
    cp ossutil-2.2.0-linux-amd64/ossutil /opt/conda/envs/seeksoulmethyl/bin/ && \
    chmod +x /opt/conda/envs/seeksoulmethyl/bin/ossutil && \
    rm -rf ossutil-2.2.0-linux-amd64.zip ossutil-2.2.0-linux-amd64

RUN mkdir -p ~/.nextflow/plugins/nf-k8s-1.2.2 && cd ~/.nextflow/plugins/nf-k8s-1.2.2 && \
    wget https://registry.nextflow.io/api/v1/plugins/nf-k8s/1.2.2/download/nf-k8s-1.2.2.zip && \
    unzip nf-k8s-1.2.2.zip && \
    rm -rf nf-k8s-1.2.2.zip

##   test

CMD ["/bin/bash"]
